const vocab = [
  {word:  "Abuse", definition:"濫用/虐待 - The improper use or cruel treatment."},
{ word: "Abandon", definition: "拋棄/放棄 - To leave completely or give up."},
{ word: "Abundant", definition: "豐富的/充裕的 - Existing in large quantities."},
{ word: "Ample", definition: "充足的/豐富的 - Enough and often more than needed."},
{ word: "Accommodate", definition: "容納/適應/提供住宿 - To provide for or make suitable adjustments."},
{ word: "Anxiety", definition: "焦慮 - A feeling of worry or nervousness."},
{ word: "Anxious", definition: "焦慮的 - Feeling or showing worry."},
{ word: "Associate", definition: "聯繫/聯想/同事 - To connect; a partner or colleague."},
{ word: "Accompany", definition: "陪伴/陪同 - To go with or be present with."},
{ word: "Abhorrent", definition: "可憎的/令人厭惡的 - Causing disgust and hatred."},
{ word: "Aptitude", definition: "天資/才能 - A natural talent or inclination."},
{ word: "Accountability", definition: "責任/問責 - Responsibility for one's actions."},
{ word: "Acquire", definition: "獲得/取得 - To buy or obtain for oneself."},
{ word: "Acknowledge", definition: "承認/確認 - To accept or admit the truth of."},
{ word: "Adverse", definition: "不利的/相反的 - Preventing success; unfavorable."},
{ word: "Ambition", definition: "抱負/野心 - A strong desire for achievement."},
{ word: "Ambitious", definition: "有抱負的/野心勃勃的 - Having a strong desire for success."},
    { word: "Resilient", definition: "Able to withstand or recover quickly from difficult conditions." },
      { word: "Amusement", definition: "樂趣 (The state of finding something funny or entertaining)" },
  { word: "Anonymous", definition: "匿名的 (Not identified by name; of unknown authorship)" },
  { word: "Boredom", definition: "無聊, 厭倦 (The state of feeling weary and restless through lack of interest)" },
  { word: "Bother", definition: "擔心, 苦惱 (To take the trouble to do something or to cause worry)" },
  { word: "Brilliant", definition: "優秀的 (Exceptionally clever, talented, or bright)" },
  { word: "Brutal", definition: "殘忍的, 冷酷的 (Savagely violent; harsh or ruthless)" },
  { word: "Bountiful", definition: "慷慨的, 寬大的 (Large in quantity; abundant or generous)" },
  { word: "Beverage", definition: "飲料 (A drink other than water)" },
  { word: "Benevolent", definition: "仁慈的 (Well-meaning and kindly; charitable)" },
  { word: "Belated", definition: "誤期的 (Coming or happening later than should have been the case)" },
  { word: "Brazen", definition: "厚顏無恥的 (Bold and without shame)" },
  { word: "Bashful", definition: "害羞的 (Reluctant to draw attention to oneself; shy)" },
  { word: "Commitment", definition: "承諾 (The state or quality of being dedicated to a cause or activity)" },
  { word: "Commotion", definition: "騷動, 喧鬧 (A state of confused and noisy disturbance)" },
  { word: "Concise", definition: "簡潔的, 簡要的 (Giving a lot of information clearly and in a few words)" },
  { word: "Compassion", definition: "憐憫, 同情 (Sympathetic pity and concern for the sufferings of others)" },
  { word: "Compensate", definition: "賠償 (To give someone something in recognition of loss or injury)" },
  { word: "Complicated", definition: "複雜的 (Difficult to analyze or understand due to complexity)" },
  { word: "Conceal", definition: "隱瞞 (To keep from sight; to hide)" },
  { word: "Compliment", definition: "讚美的話 (A polite expression of praise or admiration)" },
  { word: "Confess", definition: "供認 (To admit that one has committed a crime or done wrong)" },
  { word: "Consent", definition: "同意 (Permission for something to happen; agreement)" },
  { word: "Concurrence", definition: "同意 (The fact of two or more events happening at the same time; agreement)" },
  { word: "Conflict", definition: "衝突 (A serious disagreement or argument)" },
  { word: "Confuse", definition: "使困惑 (To cause someone to become bewildered or perplexed)" },
  { word: "Connotation", definition: "隱含意義 (An idea or feeling that a word invokes beyond its literal meaning)" },
  { word: "Consequence", definition: "後果 (A result or effect of an action or condition)" },
  { word: "Considerate", definition: "考慮周到的 (Careful not to cause inconvenience or hurt to others)" },
  { word: "Charm", definition: "魅力 (The power or quality of giving delight or arousing admiration)" },
  { word: "Charisma", definition: "魅力 (Compelling attractiveness that can inspire devotion in others)" },
  { word: "Command", definition: "命令 (An authoritative order)" },
  { word: "Commend", definition: "稱讚 (To praise formally or officially)" },
  { word: "Controversial", definition: "爭論的 (Giving rise to public disagreement)" },
  { word: "Courteous", definition: "謙恭的 (Polite, respectful, or considerate in manner)" },
  { word: "Contempt (for)", definition: "輕視 (The feeling that a person or a thing is beneath consideration)" },
  { word: "Consistent (with)", definition: "一致的 (Acting or done in the same way over time)" },
  { word: "Crime", definition: "罪行 (An action that constitutes an offense punishable by law)" },
  { word: "Career", definition: "職業 (An occupation undertaken for a significant period of a person's life)" },
  { word: "Captivated", definition: "使著迷 (To attract and hold the interest and attention of)" },
  { word: "Candid", definition: "公正的 (Truthful and straightforward; frank)" },
  { word: "Chaos", definition: "無秩序狀態 (Complete disorder and confusion)" },
  { word: "Dump", definition: "To get rid of something or someone 拋棄" },
  { word: "Decent", definition: "Of a good enough standard; honest 體面的" },
  { word: "Dare(to)", definition: "To be brave enough to do something 敢" },
  { word: "Defensive", definition: "Protecting oneself from criticism 防備批評的" },
  { word: "Defective", definition: "Having a fault or flaw 有缺陷的" },
  { word: "Disobedient", definition: "Refusing to obey rules 不服從的" },
  { word: "Delighted", definition: "Very pleased or happy 愉快的" },
  { word: "Demolish", definition: "To pull or knock down a building 拆毀" },
  { word: "Definitely", definition: "Without any doubt 明顯地" },
  { word: "Depression", definition: "A state of feeling very sad 憂傷" },
  { word: "Depart (from)", definition: "To leave a place 出發; 離開" },
  { word: "Disabled", definition: "Having a physical or mental condition 殘疾的" },
  { word: "Despair", definition: "The complete loss of hope 絕望" },
  { word: "Dignity", definition: "Self-respect; being worthy of honor 尊嚴" },
  { word: "Diligence", definition: "Careful and persistent work 勤勉" },
  { word: "Disastrous", definition: "Causing great damage 災難性的" },
  { word: "Disaster", definition: "A sudden accident or misfortune 災害" },
  { word: "Dull", definition: "Boring; not bright 乏味的" },
  { word: "Duration", definition: "The length of time something lasts 持續時間" },
  { word: "Earnest", definition: "Serious and sincere 誠摯的" },
  { word: "Eccentric", definition: "Strange or unusual 古怪的" },
  { word: "Efficient", definition: "Working well without wasting time 效率高的" },
  { word: "Effort", definition: "Physical or mental energy 力氣" },
  { word: "Embarrassing", definition: "Feeling ashamed or shy 窘迫" },
  { word: "Emergency", definition: "A serious, unexpected situation 緊急情況" },
  { word: "Emotional", definition: "Relating to emotions 感情用事的" },
  { word: "Endure", definition: "To suffer patiently 忍耐" },
  { word: "Engrave", definition: "To cut words into a surface 銘刻在" },
  { word: "Epidemic", definition: "A widespread infectious disease 流行病" },
  { word: "Exaggeration", definition: "Making something seem bigger than it is 誇張" },
  { word: "Exemption", definition: "Being free from an obligation 被排除的" },
  { word: "Fidelity", definition: "Faithfulness to a person or cause 忠貞" },
  { word: "Falter", definition: "To lose strength or hesitate 猶豫" },
  { word: "Fantasy", definition: "Imagining impossible things 幻想" },
  { word: "Favor", definition: "To feel or show approval 贊成" },
  { word: "Feasible", definition: "Possible to do easily 可行的" },
  { word: "Flair", definition: "A natural talent or ability 天賦" },
  { word: "Flamboyant", definition: "Noticeable and stylish 炫耀的" },
  { word: "Flexible", definition: "Able to change easily 可變通的" },
  { word: "Forbid", definition: "To refuse to allow something 禁止" },
  { word: "Forbidden", definition: "Not allowed; banned 被禁止的" },
  { word: "Furious", definition: "Extremely angry 狂怒的" },
  { word: "Fruitful", definition: "Producing good results 豐饒的" },
  { word: "Frustrate", definition: "To prevent someone from succeeding 挫敗" },
  { word: "Fortunate", definition: "Favored by luck; lucky 幸運的" },
  { word: "Frank", definition: "Open, honest, and direct 坦率的" },
  { word: "Gambling", definition: "Playing games of chance for money 賭博" },
  { word: "Garbage", definition: "Wasted or spoiled food 垃圾" },
  { word: "Giggle", definition: "To laugh in a silly way 咯咯地笑" },
  { word: "Gathering", definition: "An assembly or meeting 集會" },
  { word: "Genuine", definition: "Truly what something is said to be 真的" },
  { word: "Glimpse", definition: "A quick, partial view 瞥見" },
  { word: "Gorgeous", definition: "Beautiful; very attractive 燦爛的" },
  { word: "Graceful", definition: "Having elegance or beauty 優美的" },
  { word: "Grasp", definition: "To seize and hold firmly 抓牢" },
  { word: "Greet", definition: "To give a polite word of welcome 問候" },
  { word: "Grief", definition: "Intense sorrow 悲痛" },
  { word: "Grievance", definition: "A real or imagined wrong 不平" },
  { word: "Handicap", definition: "A condition that restricts movement 殘障" },
  { word: "Happen", definition: "To take place; occur 發生" },
  { word: "Harass", definition: "To subject to aggressive pressure 騷擾" },
  { word: "Sexual harassment", definition: "Harassment involving sexual remarks 性騷擾" },
  { word: "Harsh", definition: "Unpleasantly rough or cruel 殘酷的" },
  { word: "Hatred", definition: "Intense dislike; hate 憎惡" },
  { word: "Hazard", definition: "A danger or risk 危險" },
  { word: "Hygiene", definition: "Conditions to maintain health 衞生" },
  { word: "Hygienic", definition: "Conducive to maintaining health 衞生的" },
  { word: "Hesitate", definition: "To pause before saying or doing 猶豫" },
  { word: "Humorous", definition: "Causing lighthearted laughter 幽默的" },
  { word: "Hilarious", definition: "Extremely funny 極有趣的" },
  { word: "Ignore", definition: "To refuse to take notice of 忽視" },
  { word: "Illegal", definition: "Contrary to or forbidden by law 違法的" },
  { word: "Idiotic", definition: "Very stupid or silly 白癡的" },
  { word: "Identical", definition: "Exactly alike 完全相同的" },
  { word: "Illogical", definition: "Lacking sense or clear reasoning 荒謬的" },
  { word: "Imitate", definition: "To copy or simulate 仿效" },
  { word: "Impatience", definition: "Lack of patience 不耐煩的" },
  { word: "Incentive", definition: "A thing that motivates or encourages 動力" },
  { word: "Incredible", definition: "Impossible to believe 難以置信的" },
  { word: "Inevitably", definition: "As is certain to happen 不可避免地" },
  { word: "Inferior", definition: "Lower in rank, status, or quality 低級別的" },
  { word: "Influential", definition: "Having great influence 有影響力的" },
  { word: "Inherent", definition: "Existing in something as a permanent attribute 與生俱來的" },
  { word: "Innocent", definition: "Not guilty of a crime 無罪的" },
  { word: "Insult", definition: "Speak to with disrespect 辱罵" },
  { word: "Intentionally", definition: "Deliberately; on purpose 有意地" },
  { word: "Invasion", definition: "An instance of invading 侵犯" },
  { word: "Jealous", definition: "Feeling resentment toward someone's success 妒忌" },
  { word: "Justify", definition: "Show or prove to be right 證明" },
  { word: "Kidnap", definition: "Abduct someone and hold them captive 綁架" },
  { word: "Leisure", definition: "Use of free time for enjoyment 空時" },
  { word: "Lament", definition: "A passionate expression of grief 哀悼" },
  { word: "Lenient", definition: "Merciful or tolerant 寬大的" },
  { word: "Liberal", definition: "Open to new behavior or opinions 心胸寬闊的" },
  { word: "Livelihood", definition: "A means of securing the necessities of life 生計" },
  { word: "Luxurious", definition: "Extremely comfortable or elegant 奢華的" },
  { word: "Malevolent", definition: "Having a wish to do evil to others 有惡意的" },
  { word: "Mandatory", definition: "Required by law or rules 強制性的" },
  { word: "Massive", definition: "Large and heavy or solid 巨大的" },
  { word: "Memorable", definition: "Worth remembering 難忘的" },
  { word: "Mercy", definition: "Compassion or forgiveness 仁慈" },
  { word: "Mesmerize", definition: "Hold the attention of someone 使着迷" },
  { word: "Mingle", definition: "Mix or cause to mix together 使混合" },
  { word: "Naive", definition: "Showing a lack of experience 幼稚的" },
  { word: "Necessary", definition: "Required to be done 必要的" },
  { word: "Narrate", definition: "Give a spoken or written account of 敍述" },
  { word: "Neglect", definition: "Fail to care for properly 忽略" },
  { word: "Negotiate", definition: "Try to reach an agreement 談判" },
  { word: "Norm", definition: "Something that is usual or typical 準則" },
  { word: "Numerous", definition: "Great in number; many 許多的" },
  { word: "Oath", definition: "A solemn promise 誓言" },
  { word: "Obedient", definition: "Complying with orders or requests 順從的" },
  { word: "Obligation", definition: "An act to which a person is bound 職責" },
  { word: "Obvious", definition: "Easily perceived or understood 顯然的" },
  { word: "Oblivious", definition: "Not aware of what is happening 不在意的" },
  { word: "Occasion", definition: "A particular time or instance 時候" },
  { word: "Occur", definition: "To happen; take place 發生" },
  { word: "Odd", definition: "Different from what is usual; strange 奇怪的" },
  { word: "Operate", definition: "Control the functioning of 使用" },
  { word: "Opponent", definition: "Someone who competes against another 敵手" },
  { word: "Oppose", definition: "Disapprove of and attempt to prevent 反對" },
  { word: "Opportunity", definition: "A set of circumstances that makes it possible 機會" },
  { word: "Ordinary", definition: "With no special features; normal 平常的" },
  { word: "Obstacle", definition: "A thing that blocks one's way 阻礙" },
  { word: "Outspoken", definition: "Frank in stating one's opinions 直言不諱的" },
  { word: "Perseverance", definition: "Persistence in doing something despite difficulty 堅持不懈" },
  { word: "Pastime", definition: "An activity done regularly for enjoyment 消遣" },
  { word: "Patience", definition: "The capacity to accept delay or trouble 耐心" },
  { word: "Penalty", definition: "A punishment imposed for a law-breaking 處罰" },
  { word: "Petty", definition: "Of little importance; trivial 小的" },
  { word: "Poisonous", definition: "Causing illness or death if taken into the body 有毒的" },
  { word: "Possessive", definition: "Showing a desire to own 佔有慾強的" },
  { word: "Postpone", definition: "Cause or arrange to take place later 延期" },
  { word: "Potential", definition: "Having the capacity to develop into something 可能性" },
  { word: "Precaution", definition: "A measure taken in advance to prevent harm 預防措施" },
  { word: "Predict", definition: "Say or estimate that something will happen 預言" },
  { word: "Prejudice", definition: "Preconceived opinion not based on reason 偏見" },
  { word: "Prestige", definition: "Widespread respect and admiration 名望" },
  { word: "Principle", definition: "A fundamental truth or proposition 原則" },
  { word: "Prohibit", definition: "Formally forbid something by law 禁止" },
  { word: "Promote", definition: "Further the progress of; support 晉升" },
  { word: "Prosperous", definition: "Successful in material terms; flourishing 繁榮的" },
  { word: "Purchase", definition: "Acquire by paying money 購買" },
  { word: "Purpose", definition: "The reason for which something is done 目的" },
  { word: "Pride", definition: "A feeling of deep satisfaction from achievements 自豪" },
  { word: "Priceless", definition: "So precious that its value cannot be determined 極其貴重的" },
  { word: "Proud (of)", definition: "Feeling deep pleasure or satisfaction 引以為榮的" },
  { word: "Quantify", definition: "Express or measure the quantity of 以數量表示" },
  { word: "Quality", definition: "The standard of something 質量" },
  { word: "Qualify", definition: "Be entitled to a particular benefit 使具有資格" },
  { word: "Queue", definition: "A line or sequence of people 行列" },
  { word: "Quarrel", definition: "A heated argument or disagreement 爭吵" },
  { word: "Rapid", definition: "Happening in a short time or at great speed 迅速的" },
  { word: "Random", definition: "Made or done without method 隨意的" },
  { word: "Recognize", definition: "Identify from having encountered before 認出" },
  { word: "Redundant", definition: "No longer needed or useful 多餘的" },
  { word: "Remorse", definition: "Deep regret or guilt for a wrong committed 懊悔" },
  { word: "Regret", definition: "Feel sad or disappointed over something 遺憾" },
  { word: "Refuse", definition: "Indicate that one is not willing to do something 拒絕" },
  { word: "Survive", definition: "Continue to live or exist 活下來" },
  { word: "Sacrifice", definition: "An act of giving up something valued 犧牲" },
  { word: "Speechless", definition: "Unable to speak, especially from shock 啞口無言的" },
  { word: "Sentimental", definition: "Of or prompted by feelings of tenderness 多愁感善" },
  { word: "Skeptical", definition: "Not easily convinced; having doubts 懷疑論的" },
  { word: "Species", definition: "A group of living organisms 物種" },
  { word: "Special", definition: "Better, greater, or otherwise different from what is usual 特殊的" },
  { word: "Suicide", definition: "The action of killing oneself intentionally 自殺" },
  { word: "Superficial", definition: "Existing or occurring at or on the surface 表面（上）的" },
  { word: "Supernatural", definition: "Attributed to some force beyond scientific understanding 超自然的" },
  { word: "Subside", definition: "Become less intense, violent, or severe 平靜下來" },
  { word: "Tangible", definition: "Perceptible by touch 明顯的" },
  { word: "Transparent", definition: "Allowing light to pass through so that objects can be seen 透明的" },
  { word: "Trespass", definition: "Enter the owner's land or property without permission 擅自進入" },
  { word: "Terminal", definition: "Forming or situated at the end or extremity 終端的" },
  { word: "Termination", definition: "The action of bringing something or coming to an end 結束" },
  { word: "Violate", definition: "Break or fail to comply with a rule 違背" },
  { word: "Volatile", definition: "Liable to change rapidly and unpredictably 動盪不定的" },
  { word: "Variety", definition: "The quality or state of being different or diverse 多樣化" },
  { word: "Vicious", definition: "Deliberately cruel or violent 兇險的" },
  { word: "Warranty", definition: "A written guarantee 保證書" },
  { word: "Zeal", definition: "Great energy or enthusiasm 熱情" },
];

    




